"""Constants, physics tuning, palette, sprites and block font for Nightwatch 1985."""

FPS = 30
TICK = 1.0 / FPS

# ---------------------------------------------------------------- screen layout
VIEW_COLS = 64
HUD_ROWS = 1
SCAN_ROWS = 3
PLAY_ROWS = 18
MSG_ROWS = 2
VIEW_ROWS = HUD_ROWS + SCAN_ROWS + PLAY_ROWS + MSG_ROWS      # 24 terminal rows
PLAY_TOP = HUD_ROWS + SCAN_ROWS                              # first play row (4)
MSG_TOP = PLAY_TOP + PLAY_ROWS                               # first message row (22)

# ---------------------------------------------------------------- world
WORLD_W = 320            # the world wraps horizontally (5 screens wide)
WORLD_H = 72
KARMAN = 30              # rows above this are space: zero gravity, no drag
GROUND_Y = WORLD_H - 1   # the ground line
MOTHER_Y = 2             # the mothership's orbit
MOTHER_BOSS_Y = 7        # where it drops to when it comes to fight
LOST_Y = MOTHER_Y + 3    # anything carried above this is gone for good
DELIVER_Y = GROUND_Y - 4 # ship must be this low (and slow) to drop off a survivor
SHIP_LAND_Y = GROUND_Y - 2
PERSON_Y = GROUND_Y - 2
LANDER_HOVER_Y = GROUND_Y - 7

# ---------------------------------------------------------------- physics
GRAVITY = 0.02            # cells per tick^2, atmosphere only
DRAG = 0.045              # fraction of velocity lost per tick in atmosphere
IMPULSE_X_ATMO = 0.20     # velocity added per key event
IMPULSE_Y_ATMO = 0.17
MAX_VX_ATMO = 1.30
MAX_VY_ATMO = 0.60
IMPULSE_X_SPACE = 0.11
IMPULSE_Y_SPACE = 0.09
MAX_VX_SPACE = 1.20
MAX_VY_SPACE = 0.70
CRASH_VY = 0.40           # touch down faster than this and you're a fireball
FALL_KILL_ROWS = 12       # a dropped person falling further than this dies

BOLT_SPEED = 2.6
BOLT_LIFE = 26
FIRE_COOLDOWN = 5
ESHOT_LIFE = 150

# ---------------------------------------------------------------- game rules
START_LIVES = 3
START_BOMBS = 3
MAX_BOMBS = 5
MAX_SHIELD = 3
EXTRA_LIFE_EVERY = 10000
HUNTER_AFTER = 75 * FPS   # seconds into a wave before the hunter shows up
RESPAWN_TICKS = 70
BANNER_TICKS = 75

SCORE = {
    "lander": 150, "scout": 100, "drone": 200, "hunter": 250,
    "catch": 250, "deliver": 500, "mothership": 5000,
}

# ---------------------------------------------------------------- palette
# name -> (256-colour index, basic 8-colour index)
# basic: 0 black 1 red 2 green 3 yellow 4 blue 5 magenta 6 cyan 7 white
PALETTE = {
    # sky bands, top of atmosphere (0) down to the dusk horizon (6)
    "space":      (16, 0),
    "atmo0":      (17, 4),
    "atmo1":      (18, 4),
    "atmo2":      (54, 4),
    "atmo3":      (55, 5),
    "atmo4":      (90, 5),
    "atmo5":      (96, 5),
    "atmo6":      (131, 1),
    "ground":     (22, 2),
    "grass":      (34, 2),
    "karman":     (25, 6),

    "star":       (250, 7),
    "star_dim":   (243, 7),
    "moon":       (230, 7),

    # town silhouettes
    "silhouette": (16, 0),
    "window":     (226, 3),
    "beacon":     (196, 1),
    "screen":     (117, 6),
    "corn":       (100, 2),
    "hill":       (238, 0),
    "pad":        (245, 7),
    "padlight":   (51, 6),

    # the interceptor
    "ship":       (231, 7),
    "canopy":     (51, 6),
    "flame":      (208, 1),
    "flame2":     (226, 3),
    "flame_space": (39, 6),
    "shield":     (51, 6),

    # townsfolk
    "person":     (218, 5),
    "panic":      (231, 7),
    "beam":       (226, 3),
    "beam2":      (231, 7),

    # invaders
    "lander":     (46, 2),
    "lamp":       (226, 3),
    "scout":      (196, 1),
    "drone":      (201, 5),
    "hunter":     (208, 1),
    "mother":     (93, 5),
    "hatch":      (60, 4),
    "core":       (196, 1),
    "core_hit":   (231, 7),

    "bolt":       (226, 3),
    "eshot":      (208, 1),
    "plasma":     (201, 5),

    "boom0":      (231, 7),
    "boom1":      (226, 3),
    "boom2":      (208, 1),
    "boom3":      (196, 1),
    "boom4":      (240, 0),

    # chrome
    "hud_bg":     (16, 0),
    "hud":        (231, 7),
    "hud_dim":    (245, 7),
    "hud_gold":   (220, 3),
    "hud_red":    (196, 1),
    "scan":       (234, 0),
    "scan_view":  (237, 0),
    "scan_line":  (240, 0),
    "msg":        (159, 6),
    "msg_alert":  (203, 1),
    "msg_good":   (120, 2),
    "panel":      (16, 0),
    "panel_fg":   (231, 7),
    "title":      (51, 6),
    "title2":     (201, 5),
    "title3":     (220, 3),
}

# ---------------------------------------------------------------- sprites
# The interceptor, facing right.  Left-facing is generated by mirroring.
SHIP_R = (
    "  ▄▟█▙▶",
    "▜▀▀██▘ ",
)
SHIP_CANOPY = {(0, 4)}            # (row, col) cells drawn in the canopy colour

MIRROR = {
    "▟": "▙", "▙": "▟", "▜": "▛", "▛": "▜", "▶": "◀", "◀": "▶",
    "▘": "▝", "▝": "▘", "▗": "▖", "▖": "▗", "▐": "▌", "▌": "▐",
    "▚": "▞", "▞": "▚", "◢": "◣", "◣": "◢", "◥": "◤", "◤": "◥",
    "(": ")", ")": "(", "<": ">", ">": "<", "/": "\\", "\\": "/",
}


def mirror(rows):
    return tuple("".join(MIRROR.get(ch, ch) for ch in reversed(row)) for row in rows)


SHIP_L = mirror(SHIP_R)

LANDER = (
    (" ▄█▄ ", "▀▀▀▀▀"),
    (" ▄█▄ ", "▀▪▀▪▀"),
)
SCOUT = ("◀███▶",)
DRONE = ("◢█◣", "◥█◤")
HUNTER = ("◣▓▓▓◢",)
MOTHERSHIP = (
    "   ▄▄▄▄▄▄▄▄▄   ",
    "▐███▓▓▓▓▓▓▓███▌",
    "   ▀▀▀▀▀▀▀▀▀   ",
)
MOTHER_HATCH = (1, 6, 3)          # row, first col, width of the hatch
MOTHER_CORE = (1, 7)              # row, col of the core when the hatch is open

PERSON = ("●", "█")
PERSON_FALL = ("●", "▲")
BOLT = "━━"
ESHOT = "•"
PLASMA = "◆"
BEAM = ("┆", "╎")
FLAME_ATMO = ("═", "≡", "=")
FLAME_SPACE = ("·", "∙", "·")
BOOM_CHARS = ("✦", "✧", "▪", "·")

# ---------------------------------------------------------------- 3x5 block font
FONT = {
    "A": (" █ ", "█ █", "███", "█ █", "█ █"),
    "B": ("██ ", "█ █", "██ ", "█ █", "██ "),
    "C": (" ██", "█  ", "█  ", "█  ", " ██"),
    "D": ("██ ", "█ █", "█ █", "█ █", "██ "),
    "E": ("███", "█  ", "██ ", "█  ", "███"),
    "F": ("███", "█  ", "██ ", "█  ", "█  "),
    "G": (" ██", "█  ", "█ █", "█ █", " ██"),
    "H": ("█ █", "█ █", "███", "█ █", "█ █"),
    "I": ("███", " █ ", " █ ", " █ ", "███"),
    "J": ("  █", "  █", "  █", "█ █", " █ "),
    "K": ("█ █", "█ █", "██ ", "█ █", "█ █"),
    "L": ("█  ", "█  ", "█  ", "█  ", "███"),
    "M": ("█ █", "███", "███", "█ █", "█ █"),
    "N": ("██ ", "█ █", "█ █", "█ █", "█ █"),
    "O": ("███", "█ █", "█ █", "█ █", "███"),
    "P": ("██ ", "█ █", "██ ", "█  ", "█  "),
    "Q": ("███", "█ █", "█ █", "███", "  █"),
    "R": ("██ ", "█ █", "██ ", "█ █", "█ █"),
    "S": (" ██", "█  ", " █ ", "  █", "██ "),
    "T": ("███", " █ ", " █ ", " █ ", " █ "),
    "U": ("█ █", "█ █", "█ █", "█ █", "███"),
    "V": ("█ █", "█ █", "█ █", "█ █", " █ "),
    "W": ("█ █", "█ █", "███", "███", "█ █"),
    "X": ("█ █", "█ █", " █ ", "█ █", "█ █"),
    "Y": ("█ █", "█ █", " █ ", " █ ", " █ "),
    "Z": ("███", "  █", " █ ", "█  ", "███"),
    "0": ("███", "█ █", "█ █", "█ █", "███"),
    "1": (" █ ", "██ ", " █ ", " █ ", "███"),
    "2": ("███", "  █", "███", "█  ", "███"),
    "3": ("███", "  █", "███", "  █", "███"),
    "4": ("█ █", "█ █", "███", "  █", "  █"),
    "5": ("███", "█  ", "███", "  █", "███"),
    "6": ("█  ", "█  ", "███", "█ █", "███"),
    "7": ("███", "  █", "  █", "  █", "  █"),
    "8": ("███", "█ █", "███", "█ █", "███"),
    "9": ("███", "█ █", "███", "  █", "███"),
    "!": (" █ ", " █ ", " █ ", "   ", " █ "),
    "-": ("   ", "   ", "███", "   ", "   "),
    " ": ("   ", "   ", "   ", "   ", "   "),
}

# ---------------------------------------------------------------- radio chatter
RADIO_SIGHTING = [
    "KRUX: Caller reports lights over {place}!",
    "Sheriff: Something's hovering over {place}.",
    "Base: Radar contact descending on {place}. Go.",
    "KRUX: Stay indoors. Saucer spotted over {place}.",
    "Farmer: The cows are going crazy out by {place}!",
    "Base: Bogey dropping toward {place}. Intercept.",
]
RADIO_TAKEN = [
    "Sheriff: They took {name}! Right off the road!",
    "KRUX: ...we've lost contact with {name}...",
    "Base: {name} is aboard the mothership. They're gone.",
]
RADIO_SAVED = [
    "{name}: I'm okay! I'm okay! What WAS that?!",
    "Sheriff: {name} is safe. Good flying, Interceptor.",
    "{name}: Nice catch, pilot. I owe you a coffee.",
    "KRUX: {name} back on the ground, folks. Breathe easy.",
]
RADIO_CATCH = [
    "{name}: AAAAH... oh. Oh thank god. Hi.",
    "Base: You caught {name}. Now set 'em down gently.",
    "{name}: Please tell me you know how to land this.",
]
RADIO_DROPPED = [
    "Base: We lost {name}. Damn it. Catch them next time.",
    "Sheriff: ...{name} didn't make it. Keep flying, son.",
]
RADIO_SPACE = [
    "Base: You're out of the atmosphere. Zero-G, watch your drift.",
    "Base: You're in orbit. Momentum is all you've got up there.",
    "Base: Clear of the atmosphere. Nothing to push against now.",
]
RADIO_REENTRY = [
    "Base: Re-entry confirmed. Gravity's back, mind the ground.",
    "Base: You're back in the soup. Feel that weight?",
]
RADIO_BOSS = [
    "Base: MOTHERSHIP DESCENDING. Hit the core when it opens!",
]
RADIO_HUNTER = [
    "Base: Fast mover inbound, doesn't match anything. Move it!",
]
RADIO_WAVE = [
    "KRUX: Another formation on the radar. Here they come again.",
    "Base: New wave of saucers dropping from orbit. Scramble.",
    "Sheriff: More of 'em. Lord help us.",
]
RADIO_IDLE = [
    "KRUX: This is KRUX 101.5. Keep watching the skies, folks.",
    "Flo: Diner's open all night. Pie's on the house if we live.",
    "Gus: Whatever those things are, they ain't Detroit.",
    "DJ Randy: Requests are open. Somebody play something calming.",
    "Pastor Dale: The church is open. Mostly the basement.",
    "Bobby: Mom says stay inside. I can see them from the roof.",
    "Nurse Kim: Clinic's lit. Bring 'em to me if they get hurt.",
]
